required_col = ['FullStudy.Rank',
                'FullStudy.Study.ProtocolSection.IdentificationModule.NCTId',
                'FullStudy.Study.ProtocolSection.IdentificationModule.OrgStudyIdInfo.OrgStudyId',
                'FullStudy.Study.ProtocolSection.IdentificationModule.Organization.OrgFullName',
                'FullStudy.Study.ProtocolSection.IdentificationModule.Organization.OrgClass',
                'FullStudy.Study.ProtocolSection.IdentificationModule.BriefTitle',
                'FullStudy.Study.ProtocolSection.StatusModule.StatusVerifiedDate',
                'FullStudy.Study.ProtocolSection.StatusModule.OverallStatus',
                'FullStudy.Study.ProtocolSection.SponsorCollaboratorsModule.LeadSponsor.LeadSponsorName',
                'FullStudy.Study.ProtocolSection.SponsorCollaboratorsModule.LeadSponsor.LeadSponsorClass',
                'FullStudy.Study.ProtocolSection.DescriptionModule.BriefSummary',
                'FullStudy.Study.ProtocolSection.DescriptionModule.DetailedDescription',
                'FullStudy.Study.ProtocolSection.DesignModule.StudyType',
                'FullStudy.Study.ProtocolSection.EligibilityModule.EligibilityCriteria',
                'FullStudy.Study.ProtocolSection.EligibilityModule.HealthyVolunteers',
                'FullStudy.Study.ProtocolSection.EligibilityModule.Gender',
                'FullStudy.Study.ProtocolSection.EligibilityModule.MinimumAge',
                'FullStudy.Study.ProtocolSection.EligibilityModule.MaximumAge',
                'FullStudy.Study.ProtocolSection.IdentificationModule.OfficialTitle']

rename_col = {'FullStudy.Rank':'Rank',
                'FullStudy.Study.ProtocolSection.IdentificationModule.NCTId':'NCT_ID',
                'FullStudy.Study.ProtocolSection.IdentificationModule.OrgStudyIdInfo.OrgStudyId':'OrgStudyId',
                'FullStudy.Study.ProtocolSection.IdentificationModule.Organization.OrgFullName':'Organization_full_name',
                'FullStudy.Study.ProtocolSection.IdentificationModule.Organization.OrgClass':'class',
                'FullStudy.Study.ProtocolSection.IdentificationModule.BriefTitle':'Title',
                'FullStudy.Study.ProtocolSection.StatusModule.StatusVerifiedDate':'Status Date',
                'FullStudy.Study.ProtocolSection.StatusModule.OverallStatus':'Overall Status',
                'FullStudy.Study.ProtocolSection.SponsorCollaboratorsModule.LeadSponsor.LeadSponsorName':'Lead Sponsor',
                'FullStudy.Study.ProtocolSection.SponsorCollaboratorsModule.LeadSponsor.LeadSponsorClass': 'Lead Sponsor Class',
                'FullStudy.Study.ProtocolSection.DescriptionModule.BriefSummary':'BriefSummary',
                'FullStudy.Study.ProtocolSection.DescriptionModule.DetailedDescription':'DetailedDescription',
                'FullStudy.Study.ProtocolSection.DesignModule.StudyType':'StudyType',
                'FullStudy.Study.ProtocolSection.EligibilityModule.EligibilityCriteria':'EligibilityCriteria',
                'FullStudy.Study.ProtocolSection.EligibilityModule.HealthyVolunteers':'HealthyVolunteers',
                'FullStudy.Study.ProtocolSection.EligibilityModule.Gender':'Gender',
                'FullStudy.Study.ProtocolSection.EligibilityModule.MinimumAge':'MinimumAge',
                'FullStudy.Study.ProtocolSection.EligibilityModule.MaximumAge':'MaximumAge',
                'FullStudy.Study.ProtocolSection.IdentificationModule.OfficialTitle':'OfficialTitle'}